# Generated by Django 3.1 on 2020-08-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_content', models.CharField(max_length=140)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
